### ISSUE TITLE
Update to places 1.1.0

### ISSUE THREAD

**Issue by pizzolante** [AhsanMunir/Google-Places-SDK-for-Android#1]
Hi, Places version 1.1.0 causes an error in Adapter and will not work.

**Comment by AhmadIzaz** [comment]
@Leoz83 can you tell which type of error ?

**Comment by AhmadIzaz** [comment]
> Hi, Places version 1.1.0 causes an error in Adapter and will not work.
@Leoz83  can you tell which type of error?
