### ISSUE TITLE
Auto complete not Returning Results

### ISSUE THREAD

**Issue by kingnightdrifter** [AhsanMunir/Google-Places-SDK-for-Android#2]
Hi folk,

I am using your code for place search which is really a rewarded attempt. Well I am facing problem at returning 0 size of filtered result 

   results.values = filterData;
                if (filterData != null) {
                    results.count = filterData.size();
                } else {
                    results.count = 0;
                }

I am using same code that you written. Any valueable suggestion will be appreciated.

**Comment by ujll8969** [comment]
in AutocompleateAdapter

**Comment by ujll8969** [comment]
in AutocompleateAdapter change returning method.
if (results.isSuccessful()) {
            if (results.getResult() != null) {
                return new ArrayList<AutocompletePrediction>(results.getResult().getAutocompletePredictions());


            }
            return null;
        } else {
            return null;
        }
